### ISSUE TITLE
"Stáhnout testy jako archiv" - různé kódování nových řádků (CRLF)/(LF)

### ISSUE THREAD

**Issue by SecurityCze** [jirkavrba/progtester#12]
Při stažení všech testů v zabaleném archivu jsou soubory s různým kódováním nových řádků.

Pro příklad soubory z `Předměty / BI-PA1 2019/20 / Domácí úloha 03 - Poloha obdélníků`:
![image](https://user-images.githubusercontent.com/40073571/68545438-78e9f900-03cd-11ea-9249-385d7666e7a3.png)

Bylo by možné všechny soubory sjednotit?

**Comment by jirkavrba** [comment]
Jo to rozhodně není feature :smile: hodim to tam někdy v průběhu týdne asi

**Comment by jirkavrba** [comment]
Mělo by být fixed. https://github.com/jirkavrba/progtester/commit/9d522228592b08eb65b1edf32db305b5c310642c

**Comment by AdamVerner** [comment]
Možnost výběru, který line-ending se stáhne by byl nice.

**Comment by jirkavrba** [comment]
Jo to zní jako dobrá feature

**Comment by jirkavrba** [comment]
Implementováno :heavy_check_mark:
