### ISSUE TITLE
empty input data

### ISSUE THREAD

**Issue by AdamVerner** [jirkavrba/progtester#15]
#### Mám 2 podobné problémy: 
**1.**
Test ošetření vstupních dat spočíval v prázdném vstupu.
Progtester mě vykopne s tím, že je prázdný input (i když validní).

**2.**
Vstupní data jsou 3 newliny `0x0a0a0a`.
Problém stejný

konkrétně šlo o úlohu hledání min

**Comment by jirkavrba** [comment]
Done :heavy_check_mark: 
https://github.com/jirkavrba/progtester/commit/0e97f3786c89c92a7c791d52a62acb810ad69986
