### ISSUE TITLE
Možnost nahrát správný/plnohodnotný output

### ISSUE THREAD

**Issue by hrubymar10** [jirkavrba/progtester#16]
Konkrétně test [1521](https://progtester.eu/testcase/1521) má sice plnohodnotný vstup, ale ve výstupu má typické progtestové `<skipping 1987 B>`. Navrhuji, aby byla možnost minimálně u testů, které obsahují ve výstupu `<skipping XXX B>` nahrát správný výstup. V tomto případě jsem výstup vygeneroval mým programem za `5.5` zde: [1531](https://progtester.eu/testcase/1531)

Alternativní řešení:
Udělat možnost při vytváření nového testu možnost marknout nový test, jako fixed variantu testu XXX.

**Comment by jirkavrba** [comment]
Asi nechápu s tím skipping jak by to mělo fungovat...

**Comment by jirkavrba** [comment]
Jakože někdo kdo není autorem řešení by mohl nahrát plnohodnotný výstup?

**Comment by hrubymar10** [comment]
Ano, ale jestli chceš omezit "SPAM" tak si udělej regex, který zjistí, zda v právě nahrávané úloze je někde `<skipping XXX B>` a interně si jí flagni jako editovatelnou.

Nebo místo regexu použij [`strpos()`](https://www.php.net/manual/en/function.strpos.php).

**Comment by jirkavrba** [comment]
Jo to zní dobře, ale asi to udělám spíš jako možnost přidat nový test který to fixuje

**Comment by jirkavrba** [comment]
![image](https://user-images.githubusercontent.com/14146321/69554030-7082e800-0fa1-11ea-8bd3-9628fa5ce990.png)

Viděl bych tohle jako asi optimální řešení

**Comment by jirkavrba** [comment]
Mělo by být deploynuté během chvíle :heavy_check_mark:
