### ISSUE TITLE
[Feature Request] Komentáře k testům, nebo možnost přidat description

### ISSUE THREAD

**Issue by hrubymar10** [jirkavrba/progtester#19]
Narážím na test [1551](https://progtester.eu/testcase/1551) kde by se třeba i hodilo přidat koment proč to je tak, jak to je. Věřím, že by to někomu mohlo pomoct.

Řešit by se to dalo buď komentářema, které jsou sice cool, ale mohly by se zvrhnout do off-topic, nebo by se to dalo vyřešit tak, že v přidávání nového testu by bylo pole "popis" do kterého by mohl autor napsat proč je to tak, jak to je (v rámci edukace), nebo text typu "neúplná nápověda z progtestu", atd...

**Comment by jirkavrba** [comment]
Taky jsem nad tím už přemýšlel nemělo by být složité na implementaci :+1: Možná to tam hodím ještě dnes

**Comment by jirkavrba** [comment]
Už by měl probíhat deploy... :checkered_flag:
