### ISSUE TITLE
[FEATURE REQUEST] linky v nejnovějších testech

### ISSUE THREAD

**Issue by matyasrichter** [jirkavrba/progtester#4]
Názvy úloh a testů v seznamu nejnovějších by mohly být linky k nim -> ušetří to několik kliknutí.

Stejně tak v seznamu předmětů by název mohl být link, ne jen tlačítko napravo, ale nebylo by to věrný progtestu :/

**Comment by jirkavrba** [comment]
Obecně jsem přemýšlel o redesignu UX na progtesteru, sice to vypadá jako progtest ale je to nepraktický :smile:

**Comment by matyasrichter** [comment]
Hmm tak možná jako Progtest Themes? Funkčně bych se toho klidně držel

**Comment by jirkavrba** [comment]
To se mi zase nechce dělat 2 verze každé šablony :smile: Je jich tam přeci jenom kolem 12 a s přibývající funkcionalitou jich bude stále více. Asi to přepíšu do nějakého css frameworku, nebude to tak cool, ale bude to aspoň funkční :smile:

**Comment by jirkavrba** [comment]
V nové verzi (možná deploynu dnes někdy kolem 4 ráno) jsem tam přidal proklik jak na testcase tak na danou úlohu. Stránky uživatelů zatím nejsou a nevidím v tom momentálně nějaký užitek :smile: Leda že by každý měl svůj "rank" podle množství a kvality testů :smile:
![image](https://user-images.githubusercontent.com/14146321/67993414-15c7cc00-fc41-11e9-9d38-1cf5a90ee791.png)

**Comment by jirkavrba** [comment]
Prokliky společně s novým UI jsou live
