### ISSUE TITLE
Fix vysouvací Láďa

### ISSUE THREAD

**Issue by tenhobi** [jirkavrba/progtester#7]
**Aktuální chování**:

Pokud má člověk myš mezi tlačítky, viz screen, Láďa zajede.

![image](https://user-images.githubusercontent.com/5287596/68026053-c6b88000-fcae-11e9-87b8-25e2e1b8a58e.png)

**Očekávané chování**:

Láďa zajede až tehdy, když je myš mimo danou sekci tlačítek.

**Navrhované řešení**:

Přesunout vysouvací efekt z `:hover` na ten obalovací div. 👍

**Comment by jirkavrba** [comment]
Ono se to takhle chová, protože pro každý button je tam jiný Láďa :smile:

**Comment by tenhobi** [comment]
Hele ono to je vlastně asi jedno. :D
