### ISSUE TITLE
Kopírování dat pomocí tlačítka kopírovat

### ISSUE THREAD

**Issue by GabTux** [jirkavrba/progtester#8]
button class="uk-button uk-button" onclick="javascript:copy('input_data')">Kopírovat

"&" se zkopíruje jako "& amp ;". Pokud text označím a zkopíruji ručně, tak to funguje korektně.

**Comment by jirkavrba** [comment]
Kouknu na to, výstup defaultně escapuji kvůli XSS, přidám možnost přidat asserty, kde bude nejspíš sada výjimek

**Comment by jirkavrba** [comment]
Mělo by být opravené, za chvíli deploynu
https://github.com/jirkavrba/progtester/commit/5102c1510838bfb64da2ca1a122a7a2b5b1b4f42
